version: '3'

services:
  php-fpm:
    image: rosamarsky/php7.4-fpm
    volumes:
    - ./:/var/www:cached
    environment:
      DB_HOST: database
      DB_PORT: 3306
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    volumes:
    - ./:/var/www:cached
    - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
    - '8204:80'
    depends_on:
    - php-fpm

  database:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
    - 3301:3306
    volumes:
    - 'data:/var/lib/mysql'

volumes:
  data: {}
